name: Crissite
favicon: null
layout_spectrum: 0.34045
typography_spectrum: 0.21208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030407'
    - '#ab6c45'
    - '#e7945f'
    - '#5d3623'
    - '#d1b389'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
