name: Crissite
favicon: null
layout_spectrum: 0.3602888360619545
typography_spectrum: 0.5054386025294662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8617522947024554
  lightness: 0.7179986161645502
  saturation: 0.017828450072556734
  rhythmicContrast: 0.8664567430969328
purpose: []
